# Branch whitelist
branches:
  only:
    - master
# Caching of bower_components & node_modules disabled, due to an increase in delayed breakages
cache:
  npm: false
  directories: null
dist: trusty
language: node_js
node_js:
  - '12'
  - '10'
matrix:
  include:
    - node_js: '12'
      env: INTEGRATION=true
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  # - if [ $INTEGRATION == true ]; then npm run integration; else npm test; fi
after_script:
  - ./cc-test-reporter format-coverage --output reports/coverage/codeclimate.json -t lcov reports/coverage/lcov.info
  - ./cc-test-reporter upload-coverage -i reports/coverage/codeclimate.json
